version: '3.4'
services:
  camplit:
    build: .
    # Override the image's entrypoint, which otherwise runs the Dockerfile's entrypoint/cmd and exits.
    # Setting "tty: true" allows the bash session to remain alive, keeping the
    # container running; without it, bash immediately exits and the container stops.
    tty: true
    entrypoint: bash
